### ISSUE TITLE
Update image PyLadies BLR

### ISSUE THREAD

**Issue by cosimameyer** [cosimameyer/awesome-pyladies-blogs#43]
@sayantikabanik I believe there is a problem when accessing the image on Google Drive - do you have another image that is publicly accessible? (Ideally hosted somewhere on a website) If you have a link for me, I'm happy to update your entry :) 

<img width="417" alt="image" src="https://github.com/cosimameyer/awesome-pyladies-blogs/assets/7782895/57c7d8eb-c6f4-44f8-9c52-a1b155a6d216">

**Comment by sayantikabanik** [comment]
Ah, currently we don't have a webpage. I will figure out an external source to host the logo (with copyrights etc)

Meanwhile was wondering if https://drive.google.com/file/d/1JaGo_gaynie6M3G2vXBEQjdAO0Tq15gU/preview this might work out

**Comment by cosimameyer** [comment]
It doesn't - but I found another temporary solution. I moved it to an 
[`img`](https://github.com/cosimameyer/awesome-pyladies-blogs/blob/50d3e7ec246baa3ba50d4b28d08d9b28017f0006/img/pyladies_blr_logo.jpeg)
) folder. If you have a GitHub account and want to use it as your profile picture, this would also be a solution :) Let me know if you have any updates and I'll change the image accordingly 🎉
