### ISSUE TITLE
Change author's name in PyLadies South Florida entry

### ISSUE THREAD

**Issue by cosimameyer** [cosimameyer/awesome-pyladies-blogs#46]
@InessaPawson, I wondered what you think about changing the author in the PyLadies SoFlo entry to "PyLadies South Florida" instead (we have it similar with PyLadies London and PyLadies Bengaluru. We can add a new separate entry for you as well, if you want ☺️)

It currently looks like this: 

![image](https://github.com/cosimameyer/awesome-pyladies-blogs/assets/7782895/d9bba94c-8598-4303-8b44-826318ac0174)

https://botsin.space/@pyladies_bot/111294420672346089

Let me know what you think ☺️ I'm happy to make a PR with suggestions for the change.

**Comment by InessaPawson** [comment]
Sounds good to me, @cosimameyer! 
No need for an additional entry. Thank you for spreading the word about the work of PyLadies!

**Comment by cosimameyer** [comment]
Thanks so much for the quick feedback 🙌 I'll take care of the changes and send you the PR for review ☺️
