### ISSUE TITLE
Broken image/Image doesn't exist anymore

### ISSUE THREAD

**Issue by cosimameyer** [cosimameyer/awesome-pyladies-blogs#50]
@emilyriederer it looks like your image doesn't exist anymore (here's the original path: https://github.com/emilyriederer/website/blob/master/content/authors/admin/avatar.jpg?raw=true) 

<img width="312" alt="image" src="https://github.com/cosimameyer/awesome-pyladies-blogs/assets/7782895/172e06f4-65f9-425f-bfe5-508eac397ba4">

Do you have a new one that we can add? 😊 If you have a link, I'm happy to add it quickly 😊

Thank you!

**Comment by emilyriederer** [comment]
@cosimameyer Thanks for catching this and my apologies! I refactored my website over the holidays, and I didn't consider where else I might have used that link as a dependency

Could you please switch it to this path? https://avatars.githubusercontent.com/u/19798371 . That one should be persistent to any more mischief on my part

**Comment by cosimameyer** [comment]
Awesome, thanks so much ☺️ I'll update it once I'm back at my computer (later this week) 🙌
